company_blog/main/views.py
from flask import Blueprint,render_template,request,url_for,redirect,flash,abort
from flask_login import login_required,current_user
from company_blog.models import BlogCategory,BlogPost,Inquiry
from company_blog.main.forms import BlogCategoryForm,UpdateCategoryForm,BlogPostForm,BlogSearchForm,InquiryForm
from company_blog import db
from company_blog.main.image_handler import add_featured_image

main=Blueprint('main',__name__)

@main.route('/category_maintenance',methods=['GET','POST'])
@login_required
def category_maintenance():

    # query文字列から現在のページを取得
    page=request.args.get('page',1,type=int)
    blog_categories=BlogCategory.query.order_by(BlogCategory.id.asc()).paginate(page=page,per_page=10)
    form=BlogCategoryForm()
    # POSTver　データの登録といえる
    if form.validate_on_submit():
        # formは上で作ったclassのインスタンスのfieldを指している
        blog_category=BlogCategory(category=form.category.data)
        db.session.add(blog_category)
        db.session.commit()
        flash('ブログカテゴリが追加されました')
        return redirect(url_for('main.category_maintenance'))
    #   もう一回この関数が呼ばれて次はデータの表示
    elif form.errors:
        form.category.data=''
        # このflashはBlogCategoryFormのvalidateの文を出せる
        flash(form.errors['category'][0])
    # このurlにアクセスしたら、今のBlogCategoryの内容とページ情報とともにmaintenance.htmlに飛ばす　GETver　データの表示といえるよ
    return render_template('category_maintenance.html',blog_categories=blog_categories,form=form)
# viewsとしてrender_templateしてるので別のところではこのurlを呼び出すだけでBlogCategoryForm(カテゴリ一覧)がだせる

@main.route('/<int:blog_category_id>/blog_category',methods=['GET','POST'])
@login_required
def blog_category(blog_category_id):
    if not current_user.is_administrator():
        abort(403)
    blog_category=BlogCategory.query.get_or_404(blog_category_id)
    form=UpdateCategoryForm(blog_category_id)
    if form.validate_on_submit():
        blog_category.category=form.category.data
        db.session.commit()
        flash('ブログカテゴリが更新されました')
        return redirect(url_for('main.category_maintenance'))
    elif request.method=='GET':
        form.category.data=blog_category.category
    return render_template('blog_category.html',form=form)

@main.route('/<int:blog_category_id>/delete_category',methods=['GET','POST'])
@login_required
def delete_category(blog_category_id):
    if not current_user.is_administrator():
        abort(403)
    blog_category=BlogCategory.query.get_or_404(blog_category_id)
    db.session.delete(blog_category)
    db.session.commit()
    flash('ブログカテゴリが削除されました')
    return redirect(url_for('main.category_maintenance'))

@main.route('/create_post',methods=['GET','POST'])
@login_required
def create_post():
    # このformのないようページに関わるからインスタンス化するよね
    form=BlogPostForm()
    # Formに入力枠だけでなくsubmitも用意したよね。それが押されたら
    if form.validate_on_submit():
        
        # if form.picture.data:
        #     pic=add_featured_image(form.picture.data)
        # else:
        #     pic=''
        blog_post=BlogPost(title=form.title.data,text=form.text.data,featured_image=form.picture.data,summary=form.summary.data,user_id=current_user.id,category_id=form.category.data,)
        db.session.add(blog_post)
        db.session.commit()
        flash('ブログ投稿が作成されました')
        return redirect(url_for('main.blog_maintenance'))

    # POSTのときはページに行くだけ、htmlに枠はあるけど実質のフォームはBBlogPostFormなのでformも渡す
    return render_template('create_post.html',form=form)


# def category_maintenanceでDBからid順でデータ持ってきて、htmlに一緒に飛ばすかな
# paginationも忘れずに
@main.route('/blog_maintenance')
@login_required
def blog_maintenance():
    page=request.args.get('page',1,type=int)
    blog_posts=BlogPost.query.order_by(BlogPost.id.desc()).paginate(page=page,per_page=10)
    return render_template('blog_maintenance.html',blog_posts=blog_posts)

# ブログ詳細ページ
# ブログ管理ページはdbからブログデータすべてを持ってきて、それをまとめてhtmlにおくる。htmlでは、ブログ１つずつforで回す。そこで、id,titleなどの値を取り出して表示する。この表示には詳細ボタンもある。その時の.idを詳細ボタンのときのurl_forに渡すとここでの関数の引数としてそれをつかえてどのブログかわかる。
@main.route('/<int:blog_post_id>/blog_post')
def blog_post(blog_post_id):
    # idをもらったらそのidのブログをまたデータベースから持ってくる。    
    form = BlogSearchForm()
    blog_post=BlogPost.query.get_or_404(blog_post_id)

    # ブログ記事の取得
    page=request.args.get('page',1,type=int)
    blog_posts=BlogPost.query.order_by(BlogPost.id.desc()).paginate(page=page,per_page=10)

    # 最新記事の取得
    recent_blog_posts=BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリの取得
    blog_categories=BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('blog_post.html',post=blog_post,recent_blog_posts=recent_blog_posts,blog_categories=blog_categories,form=form)

@main.route('/<int:blog_post_id>/delete_blog',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):
    blog_post= BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('ブログ投稿が削除されました')
    return redirect(url_for('main.blog_maintenance'))

# 更新ボタンが押されたら、更新ページで元もページのIdを受け取ってそのIdのデータをcreate_post.htmlに送り、表示。GETなのかな。htmlで送られたものは書き換えられて同じIDのデータに上書きできるのであろうか
# BlogPostFormに入れて、validate_on_submit()でIdを指定できればいけるのかな
# A -> IDでqueryでgetしてインスタンス作ってそのそれぞれのフィールドにいれていく
@main.route('/<int:blog_post_id>/update_post',methods=['GET','POST'])
@login_required
def update_post(blog_post_id):
    blog_post=BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    form=BlogPostForm()

    if form.validate_on_submit():
        blog_post.title=form.title.data
        blog_post.category_id=form.category.data
        blog_post.text=form.text.data
        blog_post.summary=form.summary.data
        # if form.picture.data:
        #     blog_post.featured_image=add_featured_image(form.picture.data)
        blog_post.featured_image=form.picture.data
        db.session.commit()
        flash('ブログ投稿が更新されました')
        return redirect(url_for('main.blog_post',blog_post_id=blog_post.id))
    # GETの処理(ロード)とPOSTの処理(更新)
    if request.method=='GET':
        form.title.data=blog_post.title
        form.category.data=blog_post.category_id
        form.text.data=blog_post.text
        form.summary.data=blog_post.summary
        form.picture.data=blog_post.featured_image
    return render_template('create_post.html',form=form)

@main.route('/')
def index():
    form = BlogSearchForm()
    # ブログ記事の取得
    page=request.args.get('page',1,type=int)
    blog_posts=BlogPost.query.order_by(BlogPost.id.desc()).paginate(page=page,per_page=10)

    # 最新記事の取得
    recent_blog_posts=BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリの取得
    blog_categories=BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html',blog_posts=blog_posts,recent_blog_posts=recent_blog_posts,blog_categories=blog_categories,form=form)

@main.route('/search',methods=['GET','POST'])
def search():
    form=BlogSearchForm()
    searchtext=""
    if form.validate_on_submit():
        searchtext=form.searchtext.data
    elif request.method=='GET':
        form.searchtext.data=""

    # ブログ記事の取得
    page=request.args.get('page',1,type=int)
    blog_posts=BlogPost.query.filter((BlogPost.text.contains(searchtext)) | (BlogPost.title.contains(searchtext)) | (BlogPost.summary.contains(searchtext))).order_by(BlogPost.id.desc()).paginate(page=page,per_page=10)

    # 最新記事の取得
    recent_blog_posts=BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリの取得
    blog_categories=BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html',blog_posts=blog_posts,recent_blog_posts=recent_blog_posts,blog_categories=blog_categories,form=form,searchtext=searchtext)

@main.route('/<int:blog_category_id>/category_posts')
def category_posts(blog_category_id):
    form = BlogSearchForm()
    # カテゴリ名の取得
    blog_category=BlogCategory.query.filter_by(id=blog_category_id).first_or_404()

    # ブログ記事の取得
    page=request.args.get('page',1,type=int)
    blog_posts=BlogPost.query.filter_by(category_id=blog_category_id).order_by(BlogPost.id.desc()).paginate(page=page,per_page=10)

    # 最新記事の取得
    recent_blog_posts=BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリの取得
    blog_categories=BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html',blog_posts=blog_posts,recent_blog_posts=recent_blog_posts,blog_categories=blog_categories,form=form,blog_category=blog_category)

@main.route('/inquiry',methods=['GET','POST'])
def inquiry():
    form=InquiryForm()

    if form.validate_on_submit():
        inquiry=Inquiry(name=form.name.data,email=form.email.data,title=form.title.data,text=form.text.data)
        db.session.add(inquiry)
        db.session.commit()
        flash('お問い合わせが送信されました')
        return redirect(url_for('main.inquiry'))

    return render_template('inquiry.html',form=form)

@main.route('/inquiry_maintenance')
@login_required
def inquiry_maintenance():
    page=request.args.get('page',1,type=int)
    inquiries=Inquiry.query.order_by(Inquiry.id.desc()).paginate(page=page,per_page=10)
    return render_template('inquiry_maintenance.html',inquiries=inquiries)

@main.route('/<int:inquiry_id>/display_inquiry')
@login_required
def display_inquiry(inquiry_id):
    inquiry=Inquiry.query.get_or_404(inquiry_id)
    form=InquiryForm()
    form.name.data=inquiry.name
    form.email.data=inquiry.email
    form.title.data=inquiry.title
    form.text.data=inquiry.text

    return render_template('inquiry.html',form=form,inquiry_id=inquiry.id)

@main.route('/<int:inquiry_id>/delete_inquiry',methods=['GET','POST'])
@login_required
def delete_inquiry(inquiry_id):
    if not current_user.is_administrator():
        abort(403)
    inquiry=Inquiry.query.get_or_404(inquiry_id)
    db.session.delete(inquiry)
    db.session.commit()
    flash('お問い合わせが削除されました')
    return redirect(url_for('main.inquiry_maintenance'))

@main.route('/info')
def info():

company_blog/users/views.py
from flask import render_template, url_for, redirect, session, flash,request,abort
from flask_login import login_user,logout_user,login_required,current_user
from company_blog import db
from company_blog.models import User,BlogPost,BlogCategory
from company_blog.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from company_blog.main.forms import BlogSearchForm
from flask import Blueprint

users=Blueprint('users',__name__)


@users.route('/login',methods=['GET','POST'])
def login():
    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                next=request.args.get('next')
                if next==None or not next[0]=='/':
                    next=url_for('main.blog_maintenance')
                return redirect(next)
            else:
                flash('パスワードが一致しません')
        else:
            flash('入力されたユーザーは存在しません')
    return render_template('users/login.html',form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))
    
@users.route('/register',methods=['GET','POST'])
@login_required
def register():
    form = RegistrationForm()
    if not current_user.is_administrator():
        # 中止する
        abort(403)
    if form.validate_on_submit():
        # session['email']=form.email.data
        # session['username']=form.username.data
        # session['password']=form.password.data

        # データベースusersへの追加
        # form.は実際に入力されたフォームから取得
        user=User(email=form.email.data,username=form.username.data,password=form.password.data,administrator='0')
        db.session.add(user)
        db.session.commit()

        flash('ユーザーが登録されました')
        return redirect(url_for('users.maintenance'))
    return render_template('users/register.html',form=form)

@users.route('/maintenance')
@login_required
def maintenance():
    page=request.args.get('page',1,type=int)
    users=User.query.order_by(User.id).paginate(page=page,per_page=10)
    # dbのデータすべてをid順に並べてmaintenanceにおくる
    return render_template('users/maintenance.html',users=users)

@users.route('/<int:user_id>/account',methods=['GET','POST'])
@login_required
def account(user_id):
    user=User.query.get_or_404(user_id)
    if user.id != current_user.id and not current_user.is_administrator():
        abort(403)

    form=UpdateUserForm(user_id)
    if form.validate_on_submit():
        user.username=form.username.data
        user.email=form.email.data
        if form.password.data:
            user.password=form.password.data
        db.session.commit()
        flash('ユーザーアカウントが更新されました')
        return redirect(url_for('users.maintenance'))
    elif request.method=='GET':
        form.username.data=user.username
        form.email.data=user.email
    return render_template('users/account.html',form=form)

@users.route('/<int:user_id>/delete',methods=['GET','POST'])
@login_required
def delete_user(user_id):
    user=User.query.get_or_404(user_id)
    if not current_user.is_administrator():
        abort (403)
    if user.is_administrator():
        flash('管理者は削除できません')
        return redirect(url_for('users.account',user_id=user_id))
    db.session.delete(user)
    db.session.commit()
    flash('ユーザーアカウントが削除されました')
    return redirect(url_for('users.maintenance'))

@users.route('/<int:user_id>/user_posts')
@login_required
def user_posts(user_id):
    form = BlogSearchForm()
    # ユーザーの取得
    user=User.query.filter_by(id=user_id).first_or_404()

    # ブログ記事の取得
    page=request.args.get('page',1,type=int)
    blog_posts=BlogPost.query.filter_by(user_id=user_id).order_by(BlogPost.id.desc()).paginate(page=page,per_page=10)

    # 最新記事の取得
    recent_blog_post=BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリの取得
    blog_categories=BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html',blog_posts=blog_posts,recent_blog_post=recent_blog_post,blog_categories=blog_categories,form=form,user=user)

company_blog/templates/_formhelpers.html
{% macro render_field(field) %}
{{field(**kwargs)|safe}}
{% if field.errors %}
    <br>
    {%for error in field.errors%}
        {{error}}
    {%endfor%}
{% endif %}

{% endmacro %}

company_blog/templates/blog_category.html
{% extends 'base.html' %}
{%block content%}
    <section id="user_delete_btn">
        <div class="container py-3 my-3">
            <div class="row">
                <div class="col-md-3">
                    <button type="button" class="btn btn-danger w-100" data-bs-toggle="modal" data-bs-target="#delete_modal">
                        削除
                      </button>
                </div>
            </div>
        </div>
    </section>
    
    <section id="category_update">
        <div class="container my-2">
            <div class="row">
                <div class="col-lg-4 mx-auto">
                    <div class="card bg-success">
                        <div class="card-body text-light">
                            <h1>カテゴリ更新</h1>
                            <p>ブログカテゴリ情報を更新してください</p>
                            
                            
                            <form method="post">
                                {{form.hidden_tag()}}
                                <div class="mb-3">
                                    <!-- macroのつかいかたよくわからんなあ -->
                                    {{render_field(form.category,class="form-control form-control-lg",placeholder="カテゴリ名" )}}
                                </div>
                                {{form.submit(class="btn btn-outline-light w-100")}}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
                
        </div>
    </section>

    <!-- Modal -->
<div class="modal fade" id="delete_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">削除確認</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>このカテゴリを削除しますか</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <!-- 後で考えてみるか -->
          <form action="{{url_for('main.delete_category',blog_category_id=form.id)}}" method="post">
            <input type="submit" class="btn btn-danger" value="削除">
          </form>
        </div>
      </div>
    </div>
  </div>
  
  {%endblock%}

company_blog/templates/blog_post.html
{% extends "base.html" %}

{% block content %}

    <header id="page-header">
        <div class="container my-3 bg-light">
            <div class="row">
                <div class="col-md-6 m-auto text-center">
                    <h1 class="fst-italic">{{post.title}}</h1>
                    <hr>
                    <p>{{post.date.strftime('%Y/%m/%d')}} : {{post.author.username}}({{post.blogcategory.category}})</p>
                </div>
            </div>
        </div>
    </header>

    <!-- ページ明細 -->
     <div class="container my-3">
        <div class="row mb-2">

            <!-- こんてんつ -->
            <div class="col-md-8">
                <!-- ブログ投稿 -->
                 <section id="blog_post">
                    <div class="container py-2 bg-light">
                        {% if post.featured_image %}
                        <div class="mb-3" style="text-align: center">
                            <img src="{{post.featured_image}}" class="img-fluid">
                        </div>
                        {%endif%}
                        <p class="mb-3">{{post.text|safe}}</p>
                    </div>
                 </section>

                <!-- めにゅー -->
                <section id="menu">
                    <div class="container py-4 my-3 bg-light">
                        <div class="row">
                            {% if current_user.is_active %}
                                {%if post.author==current_user%}
                                    <div class="col-md-3 mb-3">
                                        <a href="{{url_for('main.update_post',blog_post_id=post.id)}}" class="btn btn-success w-100">更新</a>
                                    </div>
                                    <div class="col-md-3 mb-3">
                                        <button type="button" class="btn btn-danger w-100" data-bs-toggle="modal" data-bs-target="#delete_modal">
                                            削除
                                        </button>
                                    </div>
                                {%endif%}
                            {%endif%}
                            <div class="col-md-3">
                                <button type="button" class="btn btn-secondary w-100" onclick="history.back()">
                                    戻る
                                  </button>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            <!-- サイドバー -->
             <!-- mdは画面小さくしたときの境界がどれくらいか -->
             <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem">
                    <!-- 検索欄 -->
                     <div class="container-fluid mb-3">
                        <form action="#" class="d-flex" method="post">
                            <input type="text" class="form-control me-2" placeholder="検索するテキストを入力">
                            <button type="submit" class="btn btn-outline-success">検索</button>
                        </form>
                     </div>

                    <!-- 会社情報 -->
                     <div class="p-4 mb-2 bg-light">
                        <h4 class="fst-italic">会社情報</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem culpa at, magni provident delectus eveniet autem non, laborum accusamus cum, quae nemo maiores ea minus consequatur esse harum! Officia, accusamus.</p>

                     </div>

                    <!-- 最新記事 -->
                    <div class="p-4">
                        <h4 class="fst-italic">RECENT POST <span class="ms-2 fs-6">最新記事</span></h4>
                        <hr>
                        <ol class="list-unstyled">
                            {% for recent_post in recent_blog_posts%}
                            <li>
                                <a href="{{url_for('main.blog_post',blog_post_id=recent_post.id)}}" class="text-decoration-none">
                                    {% if recent_post.featured_image %}
                                    <img src="{{recent_post.featured_image}}" class="img-fluid" width="90" height="50">
                                    {% endif %}
                                    <span class="ms-2">{{recent_post.title| truncate(14)}}</span>
                                </a>
                            </li>
                            <hr>
                            {% endfor %}
                        </ol>
                     </div>

                    <!-- カテゴリ一覧 -->
                    <div class="p-4">
                        <h4 class="fst-italic">CATEGORY<span class="ms-2 fs-6">カテゴリ一覧</span></h4>
                        <hr>
                        <ol class="list-unstyled">
                            {% for blog_category in blog_categories %}
                            <li>
                                <a href="{{url_for('main.category_posts',blog_category_id=blog_category.id)}}" class="text-decoration-none">
                                    <span class="ms-2">{{ blog_category.category | truncate(20)}}</span>
                                </a>
                            </li>
                            <hr>
                            {% endfor %}
                        </ol>
                     </div>
                </div>
             </div>

        </div>
     </div>

    
    
    

    <!-- Modal -->
<div class="modal fade" id="delete_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">削除確認</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>このブログ投稿を削除しますか</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <form action="{{url_for('main.delete_post',blog_post_id=post.id)}}" method="post">
            <input type="submit" class="btn btn-danger" value="削除">
          </form>
        </div>
      </div>
    </div>
  </div>
  
{% endblock %}

company_blog/templates/index.html
{% extends 'base.html'%}
{% block content %}

     <header id="page-header">
        <div class="container my-3 bg-light">
            <div class="row">
                <div class="col-md-6 m-auto text-center">
                    {% if user %}
                        <h1 class="fst-italic">{{user.username}}</h1>
                        <br>
                    {% elif blog_category %}
                        <h1 class="fst-italic">{{blog_category.categpry}}</h1>
                        <br>
                    {% elif searchtext %}
                        <h1 class="fst-italic">"{{searchtext}}"の検索結果</h1>
                        <br>
                    {% else %}
                        <h1 class="fst-italic">Taro Inc. Blog</h1>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora, doloribus?</p>
                    {% endif %}
                </div>
            </div>
        </div>
     </header>

     <!-- ページ明細 -->
     <div class="container my-3">
        <div class="row mb-2">

            <!-- こんてんつ -->
            <div class="col-md-8">
                <!-- ブログ投稿 -->
                 <section id="blog_post">
                    <div class="row">
                        {% for post in blog_posts.items %}
                        <div class="col-md-6 mb-4">
                            <!-- カードの高さをそろえるにはh-100 -->
                            <div class="card h-100">
                                <div class="card-body" style="max-height:26rem;">
                                    {% if post.featured_image %}
                                    <div class="mb-3" style="text-align:center;">
                                        <img src="{{post.featured_image}}" class="img-fluid card-img-top" style="max-height: 10rem;">
                                    </div>
                                    {% endif %}
                                    <h3>
                                        <a href="{{url_for('main.blog_post',blog_post_id=post.id)}}" class="card-title text-decoration-none"><span class="fst-italic">{{post.title | truncate(14)}}</span></a>
                                    </h3>
                                    <p>{{post.date.strftime('%Y-%m-%d')}} by: {{post.author.username | truncate(10)}}</p>
                                    <p class="card-text">{{post.summary| truncate(40)}}</p>
                                    <a href="{{url_for('main.blog_post',blog_post_id=post.id)}}" class="btn btn-dark">続きを読む…</a>
                                </div>
                            </div>
                        </div>
                        {%endfor%}
                    </div>
                 </section>                
            </div>

            <!-- サイドバー -->
             <!-- mdは画面小さくしたときの境界がどれくらいか -->
             <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem">
                    <!-- 検索欄 -->
                     <div class="container-fluid mb-3">
                        <form action="{{url_for('main.search')}}" class="d-flex" method="post">
                            {{form.hidden_tag()}}
                            {{render_field(form.searchtext,class="form-control me-2",placeholder="検索するテキストを入力")}}
                            {{form.submit(class="btn btn-outline-success")}}
                        </form>
                     </div>

                    <!-- 会社情報 -->
                     <div class="p-4 mb-2 bg-light">
                        <h4 class="fst-italic">会社情報</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem culpa at, magni provident delectus eveniet autem non, laborum accusamus cum, quae nemo maiores ea minus consequatur esse harum! Officia, accusamus.</p>

                     </div>

                    <!-- 最新記事 -->
                     <div class="p-4">
                        <h4 class="fst-italic">RECENT POST <span class="ms-2 fs-6">最新記事</span></h4>
                        <hr>
                        <ol class="list-unstyled">
                            {% for recent_post in recent_blog_posts%}
                            <li>
                                <a href="{{url_for('main.blog_post',blog_post_id=recent_post.id)}}" class="text-decoration-none">
                                    {% if recent_post.featured_image %}
                                    <img src="{{recent_post.featured_image}}" class="img-fluid" width="90" height="50">
                                    {% endif %}
                                    <span class="ms-2">{{recent_post.title| truncate(14)}}</span>
                                </a>
                            </li>
                            <hr>
                            {% endfor %}
                        </ol>
                     </div>

                    <!-- カテゴリ一覧 -->
                    <div class="p-4">
                        <h4 class="fst-italic">CATEGORY<span class="ms-2 fs-6">カテゴリ一覧</span></h4>
                        <hr>
                        <ol class="list-unstyled">
                            {% for blog_category in blog_categories %}
                            <li>
                                <a href="{{url_for('main.category_posts',blog_category_id=blog_category.id)}}" class="text-decoration-none">
                                    <span class="ms-2">{{ blog_category.category | truncate(20)}}</span>
                                </a>
                            </li>
                            <hr>
                            {% endfor %}
                        </ol>
                     </div>
                </div>
             </div>

        </div>


        <nav class="my-2" aria-label="Page navigation">
            <ul class="pagination justify-content-center">
    
              <li {% if blog_posts.has_prev %}class="page-item"
                {% else %} class="page-item disabled"{%endif%}>
                <a class="page-link" href="
                {% if blog_posts.has_prev %}{{ url_for('main.index',page=blog_posts.prev_num) }} 
                {% else %}#{% endif %}
                ">前へ</a></li>
              
              
              <!-- <li class="page-item"><a class="page-link" href="#">ページNo.</a></li> -->
              {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
                {% if page_num %}
                    {% if blog_posts.page == page_num %}
                        <li class="page-item disabled"><a href="#" class="page-link">{{ page_num }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="{{url_for('main.index',page=page_num) }}">{{ page_num }}</a></li>
                    {% endif %}
                {%else%}
                    <li class="page-item disabled"><a href="#" class="page-link">&hellip;</a></li>
                {%endif%}
              {%endfor%}
    
              <li {% if blog_posts.has_next %}class="page-item"
                {% else %}class="page-item disabled"{%endif%}>
                <a class="page-link" href="
                {% if blog_posts.has_next %}{{ url_for('main.index',page=blog_posts.next_num)}}
                {% else %}#{% endif %}">次へ</a></li>
            </ul>
          </nav>

{%endblock%}