company_blog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import ValidationError,StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from company_blog.models import User

class RegistrationForm(FlaskForm):
    email=StringField('メールアドレス', validators=[DataRequired(), Email(message='正しいメールアドレスを表示してください')])
    username=StringField('ユーザー名', validators=[DataRequired()])
    password=PasswordField('パスワード', validators=[DataRequired(),EqualTo('pass_confirm',message='パスワードが一致していません')])
    pass_confirm=PasswordField('パスワード(確認)', validators=[DataRequired()])
    submit = SubmitField('登録')

    def validate_username(self,field):
        # 入力フォームに入れられた内容を引数にしてる
        # db上のusernameと比べる
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('入力されたユーザー名は既に使用されています。')
        
    def validate_email(self,field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('入力されたメールアドレスは既に使用されています。')

class UpdateUserForm(FlaskForm):
    email=StringField('メールアドレス',validators=[DataRequired(),Email(message='正しいメールアドレスを入力してください')])
    username=StringField('ユーザー名',validators=[DataRequired()])
    password=PasswordField('パスワード',validators=[EqualTo('pass_confirm',message='パスワードが一致していません')])
    pass_confirm=PasswordField('パスワード(確認)')
    submit=SubmitField('更新')

    def __init__(self,user_id, *args, **kwargs):
        super(UpdateUserForm,self).__init__(*args,**kwargs)
        self.id=user_id
    
    def validate_email(self,field):
        if User.query.filter(User.id != self.id).filter_by(email=field.data).first():
            raise ValidationError('入力されたメールアドレスは既に登録されています。')
        
    def validate_username(self,field):
        if User.query.filter(User.id != self.id).filter_by(username=field.data).first():
            raise ValidationError('入力されたユーザー名は既に登録されています。')

class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email(message='正しいメールアドレスを入力してください')])
    password=PasswordField('Password',validators=[DataRequired()])
    submit=SubmitField('ログイン')

company_blog/users/views.py
from flask import render_template, url_for, redirect, session, flash,request,abort
from flask_login import login_user,logout_user,login_required,current_user
from company_blog import db
from company_blog.models import User,BlogPost,BlogCategory
from company_blog.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from company_blog.main.forms import BlogSearchForm
from flask import Blueprint

users=Blueprint('users',__name__)


@users.route('/login',methods=['GET','POST'])
def login():
    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user is not None:
            if user.check_password(form.password.data):
                login_user(user)
                next=request.args.get('next')
                if next==None or not next[0]=='/':
                    next=url_for('main.blog_maintenance')
                return redirect(next)
            else:
                flash('パスワードが一致しません')
        else:
            flash('入力されたユーザーは存在しません')
    return render_template('users/login.html',form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))
    
@users.route('/register',methods=['GET','POST'])
@login_required
def register():
    form = RegistrationForm()
    if not current_user.is_administrator():
        # 中止する
        abort(403)
    if form.validate_on_submit():
        # session['email']=form.email.data
        # session['username']=form.username.data
        # session['password']=form.password.data

        # データベースusersへの追加
        # form.は実際に入力されたフォームから取得
        user=User(email=form.email.data,username=form.username.data,password=form.password.data,administrator='0')
        db.session.add(user)
        db.session.commit()

        flash('ユーザーが登録されました')
        return redirect(url_for('users.maintenance'))
    return render_template('users/register.html',form=form)

@users.route('/maintenance')
@login_required
def maintenance():
    page=request.args.get('page',1,type=int)
    users=User.query.order_by(User.id).paginate(page=page,per_page=10)
    # dbのデータすべてをid順に並べてmaintenanceにおくる
    return render_template('users/maintenance.html',users=users)

@users.route('/<int:user_id>/account',methods=['GET','POST'])
@login_required
def account(user_id):
    user=User.query.get_or_404(user_id)
    if user.id != current_user.id and not current_user.is_administrator():
        abort(403)

    form=UpdateUserForm(user_id)
    if form.validate_on_submit():
        user.username=form.username.data
        user.email=form.email.data
        if form.password.data:
            user.password=form.password.data
        db.session.commit()
        flash('ユーザーアカウントが更新されました')
        return redirect(url_for('users.maintenance'))
    elif request.method=='GET':
        form.username.data=user.username
        form.email.data=user.email
    return render_template('users/account.html',form=form)

@users.route('/<int:user_id>/delete',methods=['GET','POST'])
@login_required
def delete_user(user_id):
    user=User.query.get_or_404(user_id)
    if not current_user.is_administrator():
        abort (403)
    if user.is_administrator():
        flash('管理者は削除できません')
        return redirect(url_for('users.account',user_id=user_id))
    db.session.delete(user)
    db.session.commit()
    flash('ユーザーアカウントが削除されました')
    return redirect(url_for('users.maintenance'))

@users.route('/<int:user_id>/user_posts')
@login_required
def user_posts(user_id):
    form = BlogSearchForm()
    # ユーザーの取得
    user=User.query.filter_by(id=user_id).first_or_404()

    # ブログ記事の取得
    page=request.args.get('page',1,type=int)
    blog_posts=BlogPost.query.filter_by(user_id=user_id).order_by(BlogPost.id.desc()).paginate(page=page,per_page=10)

    # 最新記事の取得
    recent_blog_post=BlogPost.query.order_by(BlogPost.id.desc()).limit(5).all()

    # カテゴリの取得
    blog_categories=BlogCategory.query.order_by(BlogCategory.id.asc()).all()

    return render_template('index.html',blog_posts=blog_posts,recent_blog_post=recent_blog_post,blog_categories=blog_categories,form=form,user=user)

company_blog/templates/users/account.html
{% extends 'base.html' %}
{% block content %}
    {% if current_user.is_administrator() %}
    <section id="user_delete_btn">
        <div class="container py-3 my-3">
            <div class="row">
                <div class="col-md-3">
                    <button type="button" class="btn btn-danger w-100" data-bs-toggle="modal" data-bs-target="#delete_modal">
                        削除
                    </button>
                </div>
            </div>
        </div>
    </section>
    {% endif %}
    <section id="user_update">
        <div class="container my-2">
            <div class="row">
                <div class="col-lg-4 mx-auto">
                    <div class="card bg-success">
                        <div class="card-body text-light">
                            <h1>ユーザー更新</h1>
                            <p>ユーザー情報を更新してください</p>
                            
                            <form method="post">
                                {{form.hidden_tag()}}
                                <div class="mb-3">
                                    {{render_field(form.username, class='form-control form-control-lg',placeholder='ユーザー名')}}
                                </div>
                                <div class="mb-3">
                                    {{render_field(form.email, class='form-control form-control-lg',placeholder='メールアドレス')}}
                                </div>
                                <hr>
                                <div class="mb-3">
                                    {{render_field(form.password, class='form-control form-control-lg',placeholder='新パスワード')}}
                                </div>
                                <div class="mb-3">
                                    {{render_field(form.pass_confirm, class='form-control form-control-lg',placeholder='新パスワード(確認)')}}
                                </div>
                                {{ form.submit(class='btn btn-outline-light w-100',value='更新')}}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
                
        </div>
    </section>

    <!-- Modal -->
<div class="modal fade" id="delete_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">削除確認</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>このユーザーを削除しますか</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <form action="{{url_for('users.delete_user',user_id=form.id)}}" method="post">
            <input type="submit" class="btn btn-danger" value="削除">
          </form>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}

company_blog/templates/users/login.html
{%extends 'base.html'%}
{%block content%}
    <section id="user_login">
        <div class="container my-5">
            <div class="row">
                <div class="col-lg-4 mx-auto">
                    <div class="card bg-primary">
                        <div class="card-body text-light">
                            <h3>ログイン</h3>

                            <form method="post">
                                {{form.hidden_tag()}}
                                <div class="mb-3">
                                    {{render_field(form.email,class="form-control form-control-lg" ,placeholder="メールアドレス")}}
                                </div>
                                <div class="mb-3">
                                    {{render_field(form.password,class="form-control form-control-lg" ,placeholder="パスワード")}}
                                </div>
                                
                                {{form.submit(class='btn btn-outline-light w-100',value='ログイン')}}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
                
        </div>
    </section>
    <div class="container my-5">
        <div class="row">
            <div class="col-lg-4 mx-auto">
                <div class="card bg-primary">
                    <div class="card-body text-light">
                        <h3>テストユーザー</h3>
                        <p>email = 'a@gmail.com'</p>
                        <p>password = '1231'</p>
                    </div>
                </div>
            </div>
        </div>
            
    </div>
{%endblock%}

company_blog/templates/users/maintenance.html
{% extends "base.html" %}

{% block content %}
    <header id="header">
        <div class="container bg-light my-3 py-3">
            <div class="row">
                <div class="col-lg-6 m-auto text-center">
                    <h1>ユーザー管理</h1>
                </div>
            </div>
        </div>
        
    </header>

    {% if current_user.is_administrator() %}
    <selection id="menu">
        <div class="container bg-light">
            <div class="row">
                <div class="col-md-3 mx-3">
                    <a href="{{url_for('users.register')}}" class="btn btn-primary w-100">ユーザー登録</a>
                </div>
            </div>
        </div>
        
    </selection>
    {% endif %}

    <section id="user_list">
        <div class="container my-3">
            <div class="row">
                <div class="col-lg-9">
                    <div class="card bg-light" >
                        <div class="table-responsive">
                            <div class="card-header">
                                <h4 class="card-title">最新のユーザー</h4>
                            </div>
                                <table class="table table-striped text-nowrap">
                                    <thead class="table-dark">
                                        <tr>
                                        <th scope="col">ID</th>
                                        <th scope="col">ユーザー名</th>
                                        <th scope="col">メールアドレス</th>
                                        <th scope="col">管理者</th>
                                        <th scope="col">ブログ投稿数</th>
                                        <th scope="col">変更</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {%for user in users.items%}
                                        <tr>
                                            <td>{{user.id}}</td>
                                            <td>{{user.username | truncate(10)}}</td>
                                            <td>{{user.email | truncate(20)}}</td>
                                            <td>{{user.administrator}}</td>
                                            <td><a href="{{url_for('users.user_posts',user_id=user.id)}}">{{user.count_posts(user.id)}}</a></td>
                                            <td>
                                                {% if current_user.is_administrator() or current_user.id == user.id %}
                                                <a href="{{url_for('users.account',user_id=user.id)}}" class="btn btn-secondary">変更</a>
                                                {%endif%}
                                            </td>
                                        </tr>
                                        {%endfor%}
                                    
                                    </tbody>
                                </table>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </section>

    <nav class="my-2" aria-label="Page navigation">
        <ul class="pagination justify-content-center">

          <li {% if users.has_prev %}class="page-item"
            {% else %} class="page-item disabled"{%endif%}>
            <a class="page-link" href="
            {% if users.has_prev %}{{ url_for('users.maintenance',page=users.prev_num) }} 
            {% else %}#{% endif %}
            ">前へ</a></li>
          
          
          <!-- <li class="page-item"><a class="page-link" href="#">ページNo.</a></li> -->
          {% for page_num in users.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            {% if page_num %}
                {% if users.page == page_num %}
                    <li class="page-item disabled"><a href="#" class="page-link">{{ page_num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{url_for('users.maintenance',page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
            {%else%}
                <li class="page-item disabled"><a href="#" class="page-link">&hellip;</a></li>
            {%endif%}
          {%endfor%}

          <li {% if users.has_next %}class="page-item"
            {% else %}class="page-item disabled"{%endif%}>
            <a class="page-link" href="
            {% if users.has_next %}{{ url_for('users.maintenance',page=users.next_num)}}
            {% else %}#{% endif %}">次へ</a></li>
        </ul>
      </nav>

{% endblock %}

company_blog/templates/users/register.html
 {% extends "base.html" %}

 {% block content %}
 <section id="user_register">
        <div class="container my-5">
            <div class="row">
                <div class="col-lg-4 mx-auto">
                    <div class="card bg-primary">
                        <div class="card-body text-light">
                            <h1>ユーザー登録</h1>
                            <p>ユーザー情報を入力してください</p>
                            
                            <form method="post">
                                {{ form.hidden_tag() }}
                                <div class="mb-3">
                                    {{render_field(form.username, placeholder="ユーザー名",class="form-control form-control-lg")}}
                                </div>
                                <div class="mb-3">
                                    {{render_field(form.email, placeholder="メールアドレス",class="form-control form-control-lg")}}
                                </div>
                                <div class="mb-3">
                                    {{render_field(form.password, placeholder="パスワード",class="form-control form-control-lg")}}                               
                                </div>
                                <div class="mb-3">
                                    {{render_field(form.pass_confirm, placeholder="パスワード(確認)",class="form-control form-control-lg")}}
                                </div>
                                {{form.submit(class="btn btn-outline-light w-100")}}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
                
        </div>
    </section>
{% endblock %}